### ISSUE TITLE
Add support for FileLayerReader

### ISSUE THREAD

**Issue by kellyi** [rajadain/trelliscope#19] opened 2018-06-21 16:15 UTC
Currently users can query layers on S3. For ingests, however, we typically want to perform a portion of an ingest locally and write the values back out locally using FileLayerWriter so that we can verify the manifest before commencing the full ingest.

Adding support for FileLayerReader types would allow users to visualize the tiles from local ingests without having to upload the RDD to S3.

**Comment by rajadain** [comment] 2018-06-21 16:19
Duplicate of #13. Good find about the `FileLayerReader` type though, we'll probably use that when making this.

**Closed as completed by rajadain** 2018-06-21 16:19 UTC
